### ISSUE TITLE
Atribute Error

### ISSUE THREAD

**Issue by cmvac** [LightberryEu/plugin.program.hyperion.configurator#1]
Hi guys, thanks for the development of this addon. I have an issue to report, it all goes well until it tries to restart Hyperion. After that, I get the following error:

AttributeError ("list" object has no attribute "hscan_to_dict",)

After this, I opened the hyperion.config.json file and it didn't change anything. Please note that I had already a personalized file when I tried the addon. Maybe that's why it didn't work. 

It would also be nice if you would include an option to turn the grabber on and off (or an addon for that specific function). I would do it myself, but my python knowledge is still weak.

Thanks once again, i believe this addon will do wonders once you solve all of its beta issues.

**Comment by tociek** [comment]
Thanks a lot for your feedback. I will handle that in the evening... Could you tell me exact values that you entered as number leds in horizontal and vertical direction? Have you chosen "Left and goes up" or "Right and goes up"?

As for turning off/on grabber - i am not sure if this is possible without restarting hyperion (incl. startup sequence). If that wouldn't bother you, then it is definitely doable.

**Comment by cmvac** [comment]
I chose 16h x 10v, "left and goes up". As for restarting hyperion, I think that would be no issue. It would be nice to turn it off, when we are not watching TV from the tuner or from an outside source. Also would be cool to know if Retroarch for RPI would work with Hyperion.Here is the link: 

http://openelec.tv/forum/128-addons/72972-retroarch-addon-arm-rpi

But maybe that's just wishful thinking ;)

**Comment by tociek** [comment]
I haven't forgot, just found more bugs :) 

I will commit the fixes tomorrow.

**Comment by tociek** [comment]
Please check the newest release. I believe I fixed the issue - I hope I am right :)

Let me know.

Thanks
Jacek

**Comment by cmvac** [comment]
Hi Tociek, only got to try it now. It works, although the LEDs are not not centered, because I didn't star my LED from the corners, but from the middle of the TV. It would also be nice to have that option.

Thanks!

**Comment by tociek** [comment]
Thanks. I will add this option. (kind of expected this request :) ) 

I will close this issue and open another one as feature request.
