### ISSUE TITLE
IO error

### ISSUE THREAD

**Issue by svuillemenot** [LightberryEu/plugin.program.hyperion.configurator#3]
Hi , 

Thanks a lot for this development !
I installed it and tried to run it, but I get an IOError message (file does not exist) after the last step (once grabber detected).
Would you have a clue on the reason ?

I can provide you with more details upon request.

Cheers, 

Stéphane

**Comment by tociek** [comment]
Thanks for using it :) 

Could you tell me which operating system are you using? 

Jacek

**Comment by svuillemenot** [comment]
Sure, sorry : Raspbmc

Stephane

**Comment by tociek** [comment]
Quick update - I am waiting on hyperion being added to OSMC app store to make sure I am working on the final setup (OSMC is missing some tools that are normally present in other systems - like lsusb or killall)

**Comment by twenty-thr23** [comment]
Any update on this?

your work and answer is highly appreciated!

Thank you!

**Comment by tociek** [comment]
It should work with OSMC already. Raspbmc (as it is obsolete ) will not be
supported.

pt., 11 mar 2016, 18:24 użytkownik twenty-thr23 <notifications@github.com>
napisał:
