### ISSUE TITLE
Lightberry on Wetek

### ISSUE THREAD

**Issue by younes200** [LightberryEu/plugin.program.hyperion.configurator#4]
Hi,
I'm getting `/storage/hyperion/bin/hyperiond: error while loading shared libraries: libbcm_host.so` using the configuration described here : http://raspberry-at-home.com/wetek-play-with-lightberry-hd-usb-and-openelec/
Any idea to fix that ?
Thanks

**Comment by tociek** [comment]
Are you getting this error when trying to run plugin in kodi or when you try starting hyperion from command line?

**Comment by younes200** [comment]
when you try starting hyperion. I end up using OpenELEC 6.0.0 for Wetek Play provided on the website http://lightberry.eu/. `libbcm_host.so` is specific for RPi. how did you fix the hyperion to work with Wetek/AmLogic ?
