### ISSUE TITLE
oserror 2 no such file or directory

### ISSUE THREAD

**Issue by Osrike** [LightberryEu/plugin.program.hyperion.configurator#5]

**Comment by Osrike** [comment]
Hi, I have openelec 6 installed, have installed the lightberry config app, run as required but get OS 2 error....the LEDs run rgb on boot but nothing after this. anyone else have this error?

**Comment by tociek** [comment]
Please provide exact error message and the step of the wizard when the error shows up. 
Please make sure your sd card is not write protected (locked)

**Comment by Osrike** [comment]
The exact error message is :

Oserror(2 no such file or directory 

And it's happen just after configured the direction of the led. 

I choose right corner goes up, the log say that it will restart and the message error appeared. I think it's just before the rainbow. 

My sd card is unlocked.

**Comment by tociek** [comment]
Have you changed the host name in openelec?

**Comment by Osrike** [comment]
No, the host name is the same...

**Comment by tociek** [comment]
I will prepare debug version of the code over the weekend and let you know.

**Comment by Osrike** [comment]
Ok thanks you!

**Comment by tociek** [comment]
Could you send me the output of:
ls -l /storage/.config
ls -l /storage/hyperion/bin/
ls -l /storage/.kodi/addons/
ls -l /storage/.kodi/addons/plugin.program.hyperion.configurator-master/hyperion.config.new
?

**Comment by twenty-thr23** [comment]
**1.**

total 14
drwxr-xr-x    2 root     root          1024 Jan  1  1970 aacs
-rw-r--r--    1 root     root           282 Jan  1  1970 hosts.conf
drwxr-xr-x    2 root     root          1024 Jan  1  1970 hwdb.d
drwxr-xr-x    2 root     root          1024 Jan  1  1970 modprobe.d
drwxr-xr-x    2 root     root          1024 Jan  1  1970 modules-load.d
drwxr-xr-x    2 root     root          1024 Jan  1  1970 rc_keymaps
-rw-r--r--    1 root     root          3860 Jan  1  1970 samba.conf.sample
drwxr-xr-x    2 root     root          1024 Jan  1  1970 sysctl.d
drwxr-xr-x    2 root     root          1024 Jan  1  1970 system.d
drwxr-xr-x    2 root     root          1024 Jan  1  1970 tmpfiles.d
drwxr-xr-x    2 root     root          1024 Jan  1  1970 udev.rules.d

**2.**
 /storage/hyperion/bin/: No such file or directory

**3.**
total 15
drwxr-xr-x    3 root     root          1024 Mar 11 21:31 metadata.album.universal
drwxr-xr-x    3 root     root          1024 Mar 11 21:31 metadata.artists.universal
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.allmusic.com
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.fanart.tv
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.htbackdrops.com
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.imdb.com
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.musicbrainz.org
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.theaudiodb.com
drwxr-xr-x    2 root     root          1024 Mar 11 21:31 metadata.common.themoviedb.org
drwxr-xr-x    3 root     root          1024 Mar 11 21:31 metadata.musicvideos.theaudiodb.com
drwxr-xr-x    3 root     root          1024 Mar 11 21:31 metadata.themoviedb.org
drwxr-xr-x    3 root     root          1024 Mar 11 21:32 metadata.tvdb.com
drwxr-xr-x    2 root     root          1024 Mar 11 21:32 packages
drwxr-xr-x    3 root     root          1024 Mar 11 21:33 plugin.program.hyperion.configurator-master
drwxr-xr-x    2 root     root          1024 Mar 11 21:32 repository.xbmc.org

**4.**
-rw-r--r--    1 root     root         27043 Mar 11 22:13 /storage/.kodi/addons/plugin.program.hyperion.configurator-master/hyperion.config.new

Thanks!

**Comment by tociek** [comment]
Ok,  so the issue is that you don't have hyperion installed. 

The plugin only generates the the config file for hyperion, but  in order to work correctly, it requires hyperion to be installed. 

Please see hyperion wiki for instalation instructions.

**Comment by acognard** [comment]
hi all, got same issue on a rpi3 this solved it
cd
wget https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
chmod +x ./install_hyperion.sh
sudo sh ./install_hyperion.sh

hope it helps

**Comment by tociek** [comment]
Addon modified - it verifies if hyperion is installed and if not, installs it (work only for OE).
